import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { blogPosts } from '../lib/data'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hugo Serif Theme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      <div className='flex  mx-auto w-11/12'>
        <div className="my-40">
        <h1  className='text-5xl font-bold' >
        Serif - A Hugo Business Theme.
        </h1>
        <p className="my-4">
        Serif contains content types for a typical business website. The theme is fully responsive, blazing fast and artfully illustrated.
        </p>
        <a>
        <p class="bg-blue-50 ">
        <p>Phone: 1800 123 000</p>
        <p><h2 class="text-pink-600">Email: hugoserif@example.com </h2>
          <Link href="/contact">
          <button class="py-2 px-4 bg-pink-500 text-white font-semibold rounded-lg shadow-md hover:bg-pink-700 focus:outline-none focus:ring-2 focus:ring-pink-400 focus:ring-opacity-75">CONTACT</button>
            </Link></p>
          </p>
        </a></div>
        <div ><Image src="/pointing.svg" alt="hugo Logo" width={2000} height={1500} /></div>
        </div>
        <div>
          {blogPosts.map((item) => (
            <div key={item.slug}>
              <div class="flex flex-row...">
              <div class="box-border h-34 w-38 p-4 border-4 .... self-center w-full xl:w-4/5 flex flex-col sm:flex-row flex-wrap px-4 xl:px:0"> 
              <div class="w-2/3 xl:w-3/4">
                <Link href={'/accounting'}>
                  <a><h2 class="tracking-wide text-pink-600 font-bold text-2xl uppercase mb-2">{item.title}</h2></a>
                </Link>
                <Link href={'/advisory'}>
                  <a><h2 class="tracking-wide text-pink-600 font-bold text-2xl uppercase mb-2">{item.title1}</h2></a>
                </Link>
                <Link href={'/sales'}>
                  <a><h2 class="tracking-wide text-pink-600 font-bold text-2xl uppercase mb-2">{item.title2}</h2></a>
                </Link>
                <Link href={'/mergers'}>
                  <a><h2 class="tracking-wide text-pink-600 font-bold text-2xl uppercase mb-2">{item.title3}</h2></a>
                </Link>
                <Link href={'/superun'}>
                  <a><h2 class="tracking-wide text-pink-600 font-bold text-2xl uppercase mb-2">{item.title4}</h2></a>
                </Link>
                <Link href={'/tax'}>
                  <a><h2 class="tracking-wide text-pink-600 font-bold text-2xl uppercase mb-2">{item.title5}</h2></a>
                </Link>
               
                <a><h2 class="tracking-wide text-pink-600 text-align-center  font-bold text-2xl uppercase mb-2">{item.title6}</h2></a>
                <a><h2 class="tracking-wide text-pink-600 font-bold text-2xl uppercase mb-2">{item.title7}</h2></a>
                <a><h2 class="tracking-wide text-pink-600 font-bold text-2xl uppercase mb-2">{item.title8}</h2></a>
              <div class="font text-black-200 text-lg">{item.content}</div>
              
            </div>
            </div>
          </div>
        </div>
          ))}
        </div>

      </main>
      <footer>
        <p class="bg-pink-600 ">
          <a><h2 class="text-pink-100 font text-mb-5">
            <p> Hugo Serif Theme </p> </h2></a>
            <div ><Image src="/github.svg"  width={50} height={30} /></div>
            <div ><Image src="/twitter.svg"  width={50} height={30} /></div></p>
      </footer>
    </div>
     
      
    
  )
}
